### ISSUE TITLE
Small typo on GitHub

### ISSUE THREAD

**Issue by BOLT04** [AnkushSinghGandhi/AnkushSinghGandhi#6]
Hi @AnkushSinghGandhi 😃, in here there is a typo: https://github.com/AnkushSinghGandhi/AnkushSinghGandhi#my-githib-stats-blogs-and-current-work where it should be "GitHub".
Let me know if it's not a typo and is intentional 👍

**Comment by AnkushSinghGandhi** [comment]
Thanx for the issue fixed that typo
